;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-electric-star
		indent-for-tab-command
		save-buffers-kill-terminal
		))

(setq mc/cmds-to-run-once
      '(
		c-electric-paren
		goto-line
		ido-find-file
		js2-mode-match-bracket
		kill-region
		))
