;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evilnc-comment-or-uncomment-lines
        indent-for-tab-command
        kill-region
        save-buffers-kill-terminal
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ))
